fix: throw error if a repo doesn't have any branches
guardian/service-catalogue pull request #444
Opened 2023-11-07 16:18 UTC by tjsilver

## What does this change?

Throws an error in `branch-protector` if the a repo doesn't have any branches. 

## Why?

We recently had problems when `branch-protector` came across a repo that was empty and thus didn't have any branches to protect  (`guardian/braze-diff-publisher`).

## How has it been verified?

2023-11-08 11:33 UTC, NovemberTang requested changes

2023-11-08 11:33 UTC, NovemberTang commented on packages/branch-protector/src/index.ts
> +	let defaultBranchName = undefined;
throwing an error would mean that the lambda fail before deleting the item off the queue, and would re-read it next time, meaning the lambda would basically fail forever until we came along and manually deleted the message. Could we handle this a different way? Maybe just skip if we find the repo to be empty or have no branches?

2023-11-09 09:53 UTC, tjsilver commented on packages/branch-protector/src/index.ts
> +	let defaultBranchName = undefined;
I did test this on CODE and it worked - see description. Happy to discuss. I agree that we could be fixing earlier in repocop.

2023-11-09 10:45 UTC, NovemberTang approved these changes

2023-11-09 10:48 UTC, merged

2023-11-09 11:14 UTC, AshCorr commented
Should this not be a warning instead of an error? Just thinking if you ever wanted to setup alerting if these lambdas failed for any reason you probably wouldn't want it to get a false positive because a repo has no branches!